# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$url = "https://go.microsoft.com/fwlink/?linkid=2026036";
$output = "myadksetup.exe";
$start_time = Get-Date;

Invoke-WebRequest -Uri $url -OutFile $output;
Write-Output "Time taken: $((Get-Date).Subtract($start_time).Seconds) second(s)";'