# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $url = "https://go.microsoft.com/fwlink/?linkid=2026036"
      $output = "adksetup.exe"
      $start_time = Get-Date
      Invoke-WebRequest -Uri $url -OutFile $(Build.SourcesDirectory)/$output
      Write-Output "Time taken: $((Get-Date).Subtract($start_time).Seconds) second(s)"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Start-Process .\adksetup.exe -ArgumentList "/quiet" -wait' 

- task: AzureCLI@1
  displayName: 'Download IoT Core Packages'
  inputs:
    azureSubscription: 'Azure'
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob download --account-name imxiotcoreteststorage --container-name imxiotcoreblobcontainer --name Windows_10_IoT_Core_ARM_Packages.msi --file $(Build.SourcesDirectory)\Windows_10_IoT_Core_ARM_Packages.msi

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $msiPath = "$(Build.SourcesDirectory)\Windows_10_IoT_Core_ARM_Packages.msi"
      dir $msiPath
      Start-Process msiexec.exe -ArgumentList @("/i $msiPath", "/quiet", "/qn", "/L*V `"$(Build.SourcesDirectory)\msi.log`"") -wait

- task: PowerShell@2
  displayName: 'Check installation'
  inputs:
    targetType: 'inline'
    script: |
      dir "C:\Program Files (x86)\Windows Kits\10\MSPackages\retail\arm\fre"
      dir "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit"

- task: PowerShell@2
  displayName: 'Install Test Certificates'
  inputs:
    targetType: 'inline'
    script: '.\imx-iotcore\build\tools\SetupCertificate.bat'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '15.0'
    platform: 'ARM'
    configuration: 'Release'
    createLogFile: true
    logFileVerbosity: 'diagnostic'